spring.application.name=spring

spring.datasource.url = jdbc:postgresql://localhost:5432/gestion_academica
spring.datasource.username = postgres
spring.datasource.password = cero

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true
